apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    storage:
      queueManager:
        class: ibmc-vpcblock-odf-general
      persistedData:
        class: ibmc-vpcblock-odf-general
      recoveryLogs:
        class: ibmc-vpcblock-odf-general